/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Add$Params as AddUserGetOrCreate$Params } from './fn/user-get-or-create/add';
export { Add as AddUserGetOrCreate } from './fn/user-get-or-create/add';
export type { Add$Params as AddGameStart$Params } from './fn/game-start/add';
export { Add as AddGameStart } from './fn/game-start/add';
export type { Add$Params as AddGameSubmitGuess$Params } from './fn/game-submit-guess/add';
export { Add as AddGameSubmitGuess } from './fn/game-submit-guess/add';
export type { Get$Params as Get$Params } from './fn/stats/get';
export { Get as Get } from './fn/stats/get';
