/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetOrCreateUser$Params as GetOrCreateUser$Params } from './fn/user-get-or-create/get-or-create-user';
export { getOrCreateUser as getOrCreateUser } from './fn/user-get-or-create/get-or-create-user';
export type { StartGame$Params as StartGame$Params } from './fn/game-start/start-game';
export { startGame as startGame } from './fn/game-start/start-game';
export type { SubmitGuess$Params as SubmitGuess$Params } from './fn/game-submit-guess/submit-guess';
export { submitGuess as submitGuess } from './fn/game-submit-guess/submit-guess';
export type { GetStats$Params as GetStats$Params } from './fn/stats/get-stats';
export { getStats as getStats } from './fn/stats/get-stats';
