/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddGameStartParameters } from '../../models/add-game-start-parameters';
import { SpGameStartResult } from '../../models/sp-game-start-result';

export interface StartGame$Params {
  
    /**
     * Parameters for dbo.spGame_Start
     */
    body: AddGameStartParameters
}

export function startGame(http: HttpClient, rootUrl: string, params: StartGame$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'value': Array<SpGameStartResult>;
'additionalValues'?: Array<Array<{
}>>;
}>> {
  const rb = new RequestBuilder(rootUrl, startGame.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application /json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'value': Array<SpGameStartResult>;
      'additionalValues'?: Array<Array<{
      }>>;
      }>;
    })
  );
}

startGame.PATH = '/api/Game/Start';
