server {
    listen 80;
    server_name wordle-fb.duckdns.org; 

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name wordle-fb.duckdns.org; 

    # SSL Configuration
    ssl_certificate     /etc/letsencrypt/live/wordle-fb.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wordle-fb.duckdns.org/privkey.pem;
    
    # Serve Angular App
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    # Proxy API requests
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}