/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SpStatsGetResult } from '../../models/sp-stats-get-result';

export interface GetStats$Params {
  deviceId?: string;
}

export function getStats(http: HttpClient, rootUrl: string, params?: GetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'value': Array<SpStatsGetResult>;
'additionalValues'?: Array<Array<{
}>>;
}>> {
  const rb = new RequestBuilder(rootUrl, getStats.PATH, 'get');
  if (params) {
    rb.query('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'value': Array<SpStatsGetResult>;
      'additionalValues'?: Array<Array<{
      }>>;
      }>;
    })
  );
}

getStats.PATH = '/api/Stats';
