/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddGameSubmitGuessParameters {
  deviceId?: string | null;
  gameId?: number | null;
  guessWord?: string | null;
}
