/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddGameSubmitGuessParameters } from '../../models/add-game-submit-guess-parameters';
import { SpGameSubmitGuessResult } from '../../models/sp-game-submit-guess-result';

export interface SubmitGuess$Params {
  
    /**
     * Parameters for dbo.spGame_SubmitGuess
     */
    body: AddGameSubmitGuessParameters
}

export function submitGuess(http: HttpClient, rootUrl: string, params: SubmitGuess$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'value': Array<SpGameSubmitGuessResult>;
'additionalValues'?: Array<Array<{
}>>;
}>> {
  const rb = new RequestBuilder(rootUrl, submitGuess.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application /json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'value': Array<SpGameSubmitGuessResult>;
      'additionalValues'?: Array<Array<{
      }>>;
      }>;
    })
  );
}

submitGuess.PATH = '/api/Game/SubmitGuess';
